openapi: 3.1.0
info:
  title: nidemall wx - OpenAPI 3.1
  description: |-
    `nidemall` server API based on the OpenAPI 3.1 specification.
  version: '1.0'
externalDocs:
  description: GitHub repository
  url: https://github.com/charlyisidore/nidemall-server
servers:
  - url: http://localhost:8360/wx
  - url: http://localhost:8080/wx
tags:
  - name: home
  - name: catalog
  - name: auth
  - name: goods
  - name: brand
  - name: cart
  - name: collect
  - name: comment
  - name: topic
  - name: search
  - name: address
  - name: express
  - name: region
  - name: order
  - name: aftersale
  - name: feedback
  - name: footprint
  - name: groupon
  - name: coupon
  - name: storage
  - name: user
  - name: issue
paths:
  /home/index:
    get:
      tags:
        - home
      summary: Homepage data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          newGoodsList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Goods'
                          couponList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Coupon'
                          channel:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1005000
                                name:
                                  type: string
                                  example: '居家'
                                iconUrl:
                                  type: string
                                  example: 'http://yanxuan.nosdn.127.net/a45c2c262a476fea0b9fc684fed91ef5.png'
                          grouponList:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1110016
                                name:
                                  type: string
                                  example: '天然硅胶宠物除毛按摩刷'
                                brief:
                                  type: string
                                  example: '顺滑平面，猫狗通用，去除死毛'
                                picUrl:
                                  type: string
                                  example: 'http://yanxuan.nosdn.127.net/3bd73b7279a83d1cbb50c0e45778e6d6.png'
                                counterPrice:
                                  type: number
                                  example: 59
                                retailPrice:
                                  type: number
                                  example: 39
                                grouponPrice:
                                  type: number
                                  example: 0
                                grouponDiscount:
                                  type: number
                                  example: 39
                                grouponMember:
                                  type: number
                                  example: 2
                                expireTime:
                                  type: string
                                  format: date-time
                                  example: '2020-12-31 00:00:00'
                          banner:
                            type: array
                            items:
                              $ref: '#/components/schemas/Ad'
                          brandList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Brand'
                          hotGoodsList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Goods'
                          topicList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Topic'
                          floorGoodsList:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1006002
                                name:
                                  type: string
                                  example: '居家'
                                goodsList:
                                  type: array
                                  items:
                                    $ref: '#/components/schemas/Goods'
  /home/about:
    get:
      tags:
        - home
      summary: Homepage about
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          qq:
                            type: string
                          address:
                            type: string
                          phone:
                            type: string
                          latitude:
                            type: string
                          name:
                            type: string
                          longitude:
                            type: string
  /catalog/index:
    get:
      tags:
        - catalog
      summary: Catalog index
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          currentCategory:
                            $ref: '#/components/schemas/Category'
                          categoryList:
                            type: array
                            items:
                              $ref: '#/components/schemas/Category'
                          currentSubCategory:
                            type: array
                            items:
                              $ref: '#/components/schemas/Category'
  /catalog/current:
    get:
      tags:
        - catalog
      summary: Catalog current
      parameters:
        - name: id
          in: query
          description: Category ID
          required: true
          schema:
            type: integer
            example: 1005000
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          currentCategory:
                            $ref: '#/components/schemas/Category'
                          currentSubCategory:
                            type: array
                            items:
                              $ref: '#/components/schemas/Category'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        errno:
          type: integer
          description: Error code
          example: 0
        errmsg:
          type: string
          description: Error message
          example: '成功'
        data:
          description: Output data
    Ad:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: '合作 谁是你的菜'
        link:
          type: string
          example: ''
        url:
          type: string
          example: 'http://yanxuan.nosdn.127.net/65091eebc48899298171c2eb6696fe27.jpg'
        position:
          type: integer
          example: 1
        content:
          type: string
          example: '合作 谁是你的菜'
        enabled:
          type: boolean
          example: true
        addTime:
          type: string
          format: date-time
          example: '2018-02-01 00:00:00'
        updateTime:
          type: string
          format: date-time
          example: '2018-02-01 00:00:00'
        deleted:
          type: boolean
          example: false
    Brand:
      type: object
      properties:
        id:
          type: integer
          example: 1001000
        name:
          type: string
          example: 'MUJI制造商'
        desc:
          type: string
          example: "严选精选了MUJI制造商和生产原料，\n用几乎零利润的价格，剔除品牌溢价，\n让用户享受原品牌的品质生活。"
        picUrl:
          type: string
          example: 'http://yanxuan.nosdn.127.net/1541445967645114dd75f6b0edc4762d.png'
        floorPrice:
          type: number
          example: 12.9
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1005000
        name:
          type: string
          example: '居家'
        keywords:
          type: string
          example: ''
        desc:
          type: string
          example: '回家，放松身心'
        pid:
          type: number
          example: 0
        iconUrl:
          type: string
          example: 'http://yanxuan.nosdn.127.net/a45c2c262a476fea0b9fc684fed91ef5.png'
        picUrl:
          type: string
          example: 'http://yanxuan.nosdn.127.net/e8bf0cf08cf7eda21606ab191762e35c.png'
        level:
          type: string
          example: 'L1'
        sortOrder:
          type: integer
          example: 2
        addTime:
          type: string
          format: date-time
          example: '2018-02-01 00:00:00'
        updateTime:
          type: string
          format: date-time
          example: '2018-02-01 00:00:00'
    Coupon:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: '限时满减券'
        desc:
          type: string
          example: '全场通用'
        tag:
          type: string
          example: '无限制'
        days:
          type: integer
          example: 10
        discount:
          type: number
          example: 5
        min:
          type: number
          example: 99
    Goods:
      type: object
      properties:
        id:
          type: integer
          example: 1116011
        name:
          type: string
          example: '蔓越莓曲奇 200克'
        brief:
          type: string
          example: '酥脆奶香，甜酸回味'
        picUrl:
          type: string
          example: 'http://yanxuan.nosdn.127.net/767b370d07f3973500db54900bcbd2a7.png'
        isHot:
          type: boolean
          example: true
        isNew:
          type: boolean
          example: true
        counterPrice:
          type: number
          example: 56
        retailPrice:
          type: number
          example: 36
    Topic:
      type: object
      properties:
        id:
          type: integer
          example: 264
        title:
          type: string
          example: '设计师们推荐的应季好物'
        subtitle:
          type: string
          example: '原创设计春款系列上新'
        price:
          type: number
          example: 29.9
        picUrl:
          type: string
          example: 'https://yanxuan.nosdn.127.net/14918201901050274.jpg'
        readCount:
          type: string
          example: '77.7k'
  securitySchemes:
    api_key:
      type: apiKey
      name: 'X-Litemall-Token'
      in: header
