openapi: 3.0.2
info:
  title: NideMall wx
  description: NideMall server API specification for WeChat Mini Programs.
  version: '1.0'
  contact: {}
externalDocs:
  description: GitHub repository
  url: https://github.com/charlyisidore/nidemall-server
servers:
  - url: http://localhost:8080/wx
  - url: http://localhost:8360/wx
tags:
  - name: address
  - name: aftersale
  - name: auth
  - name: brand
  - name: cart
  - name: catalog
  - name: collect
  - name: comment
  - name: coupon
  - name: express
  - name: feedback
  - name: footprint
  - name: goods
  - name: groupon
  - name: home
  - name: issue
  - name: order
  - name: region
  - name: search
  - name: storage
  - name: topic
  - name: user
paths:
  /address/delete:
    $ref: paths/address/delete.yaml
  /address/detail:
    $ref: paths/address/detail.yaml
  /address/list:
    $ref: paths/address/list.yaml
  /address/save:
    $ref: paths/address/save.yaml
  /aftersale/detail:
    $ref: paths/aftersale/detail.yaml
  /aftersale/list:
    $ref: paths/aftersale/list.yaml
  /aftersale/submit:
    $ref: paths/aftersale/submit.yaml
  /brand/detail:
    $ref: paths/brand/detail.yaml
  /brand/list:
    $ref: paths/brand/list.yaml
  /cart/add:
    $ref: paths/cart/add.yaml
  /cart/checked:
    $ref: paths/cart/checked.yaml
  /cart/checkout:
    $ref: paths/cart/checkout.yaml
  /cart/delete:
    $ref: paths/cart/delete.yaml
  /cart/fastadd:
    $ref: paths/cart/fastadd.yaml
  /cart/goodscount:
    $ref: paths/cart/goodscount.yaml
  /cart/index:
    $ref: paths/cart/index.yaml
  /cart/update:
    $ref: paths/cart/update.yaml
  /catalog/current:
    $ref: paths/catalog/current.yaml
  /catalog/index:
    $ref: paths/catalog/index.yaml
  /goods/category:
    $ref: paths/goods/category.yaml
  /goods/count:
    $ref: paths/goods/count.yaml
  /goods/detail:
    $ref: paths/goods/detail.yaml
  /goods/list:
    $ref: paths/goods/list.yaml
  /home/about:
    $ref: paths/home/about.yaml
  /home/index:
    $ref: paths/home/index.yaml
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Litemall-Token
