openapi: '3.1.0'
info:
  title: NideMall wx
  description: NideMall server API specification for WeChat Mini Programs.
  version: '1.0'
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  contact: {}
externalDocs:
  description: GitHub repository
  url: https://github.com/charlyisidore/nidemall-server
servers:
  - url: http://localhost:8080/wx
  - url: http://localhost:8360/wx
tags:
  - name: address
    description: Address controller
  - name: aftersale
    description: Aftersale controller
  - name: auth
    description: Auth controller
  - name: brand
    description: Brand controller
  - name: cart
    description: Cart controller
  - name: catalog
    description: Catalog controller
  - name: collect
    description: Collect controller
  - name: comment
    description: Comment controller
  - name: coupon
    description: Coupon controller
  - name: feedback
    description: Feedback controller
  - name: footprint
    description: Footprint controller
  - name: goods
    description: Goods controller
  - name: groupon
    description: Groupon controller
  - name: home
    description: Home controller
  - name: issue
    description: Issue controller
  - name: order
    description: Order controller
  - name: search
    description: Search controller
  - name: storage
    description: Storage controller
  - name: topic
    description: Topic controller
  - name: user
    description: User controller
paths:
  /address/delete:
    $ref: paths/address/delete.yaml
  /address/detail:
    $ref: paths/address/detail.yaml
  /address/list:
    $ref: paths/address/list.yaml
  /address/save:
    $ref: paths/address/save.yaml

  /aftersale/detail:
    $ref: paths/aftersale/detail.yaml
  /aftersale/list:
    $ref: paths/aftersale/list.yaml
  /aftersale/submit:
    $ref: paths/aftersale/submit.yaml

  /auth/bindPhone:
    $ref: paths/auth/bindPhone.yaml
  /auth/login_by_weixin:
    $ref: paths/auth/login_by_weixin.yaml
  /auth/login:
    $ref: paths/auth/login.yaml
  /auth/logout:
    $ref: paths/auth/logout.yaml
  /auth/regCaptcha:
    $ref: paths/auth/regCaptcha.yaml
  /auth/register:
    $ref: paths/auth/register.yaml
  /auth/reset:
    $ref: paths/auth/reset.yaml

  /brand/detail:
    $ref: paths/brand/detail.yaml
  /brand/list:
    $ref: paths/brand/list.yaml

  /cart/add:
    $ref: paths/cart/add.yaml
  /cart/checked:
    $ref: paths/cart/checked.yaml
  /cart/checkout:
    $ref: paths/cart/checkout.yaml
  /cart/delete:
    $ref: paths/cart/delete.yaml
  /cart/fastadd:
    $ref: paths/cart/fastadd.yaml
  /cart/goodscount:
    $ref: paths/cart/goodscount.yaml
  /cart/index:
    $ref: paths/cart/index.yaml
  /cart/update:
    $ref: paths/cart/update.yaml

  /catalog/all:
    $ref: paths/catalog/all.yaml
  /catalog/current:
    $ref: paths/catalog/current.yaml
  /catalog/index:
    $ref: paths/catalog/index.yaml

  /collect/addordelete:
    $ref: paths/collect/addordelete.yaml
  /collect/list:
    $ref: paths/collect/list.yaml

  /comment/count:
    $ref: paths/comment/count.yaml
  /comment/list:
    $ref: paths/comment/list.yaml
  /comment/post:
    $ref: paths/comment/post.yaml

  /coupon/exchange:
    $ref: paths/coupon/exchange.yaml
  /coupon/list:
    $ref: paths/coupon/list.yaml
  /coupon/mylist:
    $ref: paths/coupon/mylist.yaml
  /coupon/receive:
    $ref: paths/coupon/receive.yaml
  /coupon/selectlist:
    $ref: paths/coupon/selectlist.yaml

  /feedback/submit:
    $ref: paths/feedback/submit.yaml

  /footprint/delete:
    $ref: paths/footprint/delete.yaml
  /footprint/list:
    $ref: paths/footprint/list.yaml

  /goods/category:
    $ref: paths/goods/category.yaml
  /goods/count:
    $ref: paths/goods/count.yaml
  /goods/detail:
    $ref: paths/goods/detail.yaml
  /goods/list:
    $ref: paths/goods/list.yaml
  /goods/related:
    $ref: paths/goods/related.yaml

  /groupon/detail:
    $ref: paths/groupon/detail.yaml
  /groupon/join:
    $ref: paths/groupon/join.yaml
  /groupon/list:
    $ref: paths/groupon/list.yaml
  /groupon/my:
    $ref: paths/groupon/my.yaml

  /home/about:
    $ref: paths/home/about.yaml
  /home/index:
    $ref: paths/home/index.yaml

  /issue/list:
    $ref: paths/issue/list.yaml

  /order/cancel:
    $ref: paths/order/cancel.yaml
  /order/comment:
    $ref: paths/order/comment.yaml
  /order/confirm:
    $ref: paths/order/confirm.yaml
  /order/delete:
    $ref: paths/order/delete.yaml
  /order/detail:
    $ref: paths/order/detail.yaml
  /order/goods:
    $ref: paths/order/goods.yaml
  /order/list:
    $ref: paths/order/list.yaml
  /order/paynotify:
    $ref: paths/order/paynotify.yaml
  /order/prepay:
    $ref: paths/order/prepay.yaml
  /order/submit:
    $ref: paths/order/submit.yaml

  /search/clearhistory:
    $ref: paths/search/clearhistory.yaml
  /search/helper:
    $ref: paths/search/helper.yaml
  /search/index:
    $ref: paths/search/index.yaml

  /storage/upload:
    $ref: paths/storage/upload.yaml

  /topic/detail:
    $ref: paths/topic/detail.yaml
  /topic/list:
    $ref: paths/topic/list.yaml
  /topic/related:
    $ref: paths/topic/related.yaml

  /user/index:
    $ref: paths/user/index.yaml

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Litemall-Token

security: []