openapi: '3.1.0'
info:
  title: NideMall wx
  description: NideMall server API specification for WeChat Mini Programs.
  version: '1.0'
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  contact: {}
externalDocs:
  description: GitHub repository
  url: https://github.com/charlyisidore/nidemall-server
servers:
  - url: http://localhost:8080/wx
  - url: http://localhost:8360/wx
tags:
  - name: ad
    description: Ad controller
  - name: address
    description: Address controller
  - name: admin
    description: Admin controller
  - name: aftersale
    description: Aftersale controller
  - name: auth
    description: Auth controller
  - name: brand
    description: Brand controller
  - name: cart
    description: Cart controller
  - name: catalog
    description: Catalog controller
  - name: collect
    description: Collect controller
  - name: comment
    description: Comment controller
  - name: coupon
    description: Coupon controller
  - name: feedback
    description: Feedback controller
  - name: footprint
    description: Footprint controller
  - name: goods
    description: Goods controller
  - name: groupon
    description: Groupon controller
  - name: home
    description: Home controller
  - name: issue
    description: Issue controller
  - name: order
    description: Order controller
  - name: search
    description: Search controller
  - name: storage
    description: Storage controller
  - name: topic
    description: Topic controller
  - name: user
    description: User controller
paths:
  /admin/ad/create:
    $ref: paths/admin/ad/create.yaml
  /admin/ad/delete:
    $ref: paths/admin/ad/delete.yaml
  /admin/ad/list:
    $ref: paths/admin/ad/list.yaml
  /admin/ad/read:
    $ref: paths/admin/ad/read.yaml
  /admin/ad/update:
    $ref: paths/admin/ad/update.yaml

  /admin/address/list:
    $ref: paths/admin/address/list.yaml

  /admin/admin/create:
    $ref: paths/admin/admin/create.yaml
  /admin/admin/delete:
    $ref: paths/admin/admin/delete.yaml
  /admin/admin/list:
    $ref: paths/admin/admin/list.yaml
  /admin/admin/read:
    $ref: paths/admin/admin/read.yaml
  /admin/admin/update:
    $ref: paths/admin/admin/update.yaml

  /wx/address/delete:
    $ref: paths/wx/address/delete.yaml
  /wx/address/detail:
    $ref: paths/wx/address/detail.yaml
  /wx/address/list:
    $ref: paths/wx/address/list.yaml
  /wx/address/save:
    $ref: paths/wx/address/save.yaml

  /wx/aftersale/detail:
    $ref: paths/wx/aftersale/detail.yaml
  /wx/aftersale/list:
    $ref: paths/wx/aftersale/list.yaml
  /wx/aftersale/submit:
    $ref: paths/wx/aftersale/submit.yaml

  /wx/auth/bindPhone:
    $ref: paths/wx/auth/bindPhone.yaml
  /wx/auth/login_by_weixin:
    $ref: paths/wx/auth/login_by_weixin.yaml
  /wx/auth/login:
    $ref: paths/wx/auth/login.yaml
  /wx/auth/logout:
    $ref: paths/wx/auth/logout.yaml
  /wx/auth/regCaptcha:
    $ref: paths/wx/auth/regCaptcha.yaml
  /wx/auth/register:
    $ref: paths/wx/auth/register.yaml
  /wx/auth/reset:
    $ref: paths/wx/auth/reset.yaml

  /wx/brand/detail:
    $ref: paths/wx/brand/detail.yaml
  /wx/brand/list:
    $ref: paths/wx/brand/list.yaml

  /wx/cart/add:
    $ref: paths/wx/cart/add.yaml
  /wx/cart/checked:
    $ref: paths/wx/cart/checked.yaml
  /wx/cart/checkout:
    $ref: paths/wx/cart/checkout.yaml
  /wx/cart/delete:
    $ref: paths/wx/cart/delete.yaml
  /wx/cart/fastadd:
    $ref: paths/wx/cart/fastadd.yaml
  /wx/cart/goodscount:
    $ref: paths/wx/cart/goodscount.yaml
  /wx/cart/index:
    $ref: paths/wx/cart/index.yaml
  /wx/cart/update:
    $ref: paths/wx/cart/update.yaml

  /wx/catalog/all:
    $ref: paths/wx/catalog/all.yaml
  /wx/catalog/current:
    $ref: paths/wx/catalog/current.yaml
  /wx/catalog/index:
    $ref: paths/wx/catalog/index.yaml

  /wx/collect/addordelete:
    $ref: paths/wx/collect/addordelete.yaml
  /wx/collect/list:
    $ref: paths/wx/collect/list.yaml

  /wx/comment/count:
    $ref: paths/wx/comment/count.yaml
  /wx/comment/list:
    $ref: paths/wx/comment/list.yaml
  /wx/comment/post:
    $ref: paths/wx/comment/post.yaml

  /wx/coupon/exchange:
    $ref: paths/wx/coupon/exchange.yaml
  /wx/coupon/list:
    $ref: paths/wx/coupon/list.yaml
  /wx/coupon/mylist:
    $ref: paths/wx/coupon/mylist.yaml
  /wx/coupon/receive:
    $ref: paths/wx/coupon/receive.yaml
  /wx/coupon/selectlist:
    $ref: paths/wx/coupon/selectlist.yaml

  /wx/feedback/submit:
    $ref: paths/wx/feedback/submit.yaml

  /wx/footprint/delete:
    $ref: paths/wx/footprint/delete.yaml
  /wx/footprint/list:
    $ref: paths/wx/footprint/list.yaml

  /wx/goods/category:
    $ref: paths/wx/goods/category.yaml
  /wx/goods/count:
    $ref: paths/wx/goods/count.yaml
  /wx/goods/detail:
    $ref: paths/wx/goods/detail.yaml
  /wx/goods/list:
    $ref: paths/wx/goods/list.yaml
  /wx/goods/related:
    $ref: paths/wx/goods/related.yaml

  /wx/groupon/detail:
    $ref: paths/wx/groupon/detail.yaml
  /wx/groupon/join:
    $ref: paths/wx/groupon/join.yaml
  /wx/groupon/list:
    $ref: paths/wx/groupon/list.yaml
  /wx/groupon/my:
    $ref: paths/wx/groupon/my.yaml

  /wx/home/about:
    $ref: paths/wx/home/about.yaml
  /wx/home/index:
    $ref: paths/wx/home/index.yaml

  /wx/issue/list:
    $ref: paths/wx/issue/list.yaml

  /wx/order/cancel:
    $ref: paths/wx/order/cancel.yaml
  /wx/order/comment:
    $ref: paths/wx/order/comment.yaml
  /wx/order/confirm:
    $ref: paths/wx/order/confirm.yaml
  /wx/order/delete:
    $ref: paths/wx/order/delete.yaml
  /wx/order/detail:
    $ref: paths/wx/order/detail.yaml
  /wx/order/goods:
    $ref: paths/wx/order/goods.yaml
  /wx/order/list:
    $ref: paths/wx/order/list.yaml
  /wx/order/paynotify:
    $ref: paths/wx/order/paynotify.yaml
  /wx/order/prepay:
    $ref: paths/wx/order/prepay.yaml
  /wx/order/submit:
    $ref: paths/wx/order/submit.yaml

  /wx/search/clearhistory:
    $ref: paths/wx/search/clearhistory.yaml
  /wx/search/helper:
    $ref: paths/wx/search/helper.yaml
  /wx/search/index:
    $ref: paths/wx/search/index.yaml

  /wx/storage/upload:
    $ref: paths/wx/storage/upload.yaml

  /wx/topic/detail:
    $ref: paths/wx/topic/detail.yaml
  /wx/topic/list:
    $ref: paths/wx/topic/list.yaml
  /wx/topic/related:
    $ref: paths/wx/topic/related.yaml

  /wx/user/index:
    $ref: paths/wx/user/index.yaml

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-Litemall-Token
    cookieAuth:
      type: apiKey
      in: cookie
      name: thinkjs

security: []